import type { Metadata } from "next";
import "./globals.css";
import {Inter} from 'next/font/google';
import Header from "./components/header";
import SecondHeader from "./components/secondHeader";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const inter =Inter({subsets:['latin'] 
   ,variable:"--inter"})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} antialiased`}
      >
        <Header/>
        <SecondHeader/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
